# Generated by Django 5.0.3 on 2025-11-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="audio/")),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in seconds (auto-detected if possible)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rss_url", models.URLField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        default="General",
                        help_text="Category like 'World', 'Technology', 'Sports', etc.",
                        max_length=100,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional category like 'Motivational', 'Programming', etc.",
                        max_length=100,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["?"],
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "steps_json",
                    models.JSONField(
                        default=list,
                        help_text="List of step configurations in JSON format",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("once", "One-time"), ("recurring", "Recurring")],
                        default="recurring",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Specific date/time for one-time execution",
                        null=True,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        blank=True,
                        help_text="Time of day for recurring execution",
                        null=True,
                    ),
                ),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(default="User", max_length=100)),
                (
                    "default_location_name",
                    models.CharField(default="Johnson City", max_length=200),
                ),
                (
                    "default_latitude",
                    models.DecimalField(
                        decimal_places=6, default=36.3406, max_digits=9
                    ),
                ),
                (
                    "default_longitude",
                    models.DecimalField(
                        decimal_places=6, default=-82.3804, max_digits=9
                    ),
                ),
                (
                    "tts_command",
                    models.CharField(
                        default='simple_google_tts -p en "{text}"',
                        help_text="TTS command template. Use {text} as placeholder for the text to speak.",
                        max_length=500,
                    ),
                ),
                ("greeting_enabled", models.BooleanField(default=True)),
                (
                    "greeting_text",
                    models.CharField(
                        default="Good morning, {name}!",
                        help_text="Greeting template. Use {name} as placeholder.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profile",
            },
        ),
        migrations.CreateModel(
            name="RoutineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "step_details",
                    models.JSONField(
                        default=dict, help_text="Details about each step's execution"
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="alarm_app.routine",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["state", "city"],
                "unique_together": {("latitude", "longitude")},
            },
        ),
    ]
